rom: /home/ubuntu/Desktop/b-k-aarch64/baserom.us.v11.z64
endian: big
arch: mips
segments:
- - 0
  - 4096
  - header
- - 4096
  - 8388608
  - code
- - 8388608
  - 9437184
  - data
- - 9437184
  - 10485760
  - assets
symbols: symbols.txt
offsets: []
